export const START_ENTITY_EDITING = 'START_ENTITY_EDITING';
export const STOP_ENTITY_EDITING = 'STOP_ENTITY_EDITING';

export const UPDATE_ENTITY_FIELD = 'UPDATE_ENTITY_FIELD';
export const ADD_NEW_ENTITY = 'ADD_NEW_ENTITY';

export const FETCH_ENTITIES = 'FETCH_ENTITIES';
export const ENTITIES_FETCH_SUCCEEDED = 'ENTITIES_FETCH_SUCCEEDED';
export const ENTITY_FETCH_SUCCEEDED = 'ENTITY_FETCH_SUCCEEDED';

export const REMOVE_ENTITY = 'REMOVE_ENTITY';
export const REMOVE_NEW_ENTITY = 'REMOVE_NEW_ENTITY';
export const ENTITY_REMOVE_SUCCEEDED = 'ENTITY_REMOVE_SUCCEEDED';